<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2013-2025 chronicle.software; SPDX-License-Identifier: Apache-2.0

-->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>net.openhft</groupId>
        <artifactId>java-parent-pom</artifactId>
        <version>1.27ea1</version>
        <relativePath />
    </parent>

    <artifactId>Java-Thread-Affinity</artifactId>
    <version>3.27ea2-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>OpenHFT/Java-Thread-Affinity Parent</name>
    <description>Java Thread Affinity library</description>

    <modules>
        <module>affinity</module>
        <module>affinity-test</module>
    </modules>

    <scm>
        <url>scm:git:git@github.com:OpenHFT/Java-Thread-Affinity.git</url>
        <connection>scm:git:git@github.com:OpenHFT/Java-Thread-Affinity.git</connection>
        <developerConnection>scm:git:git@github.com:OpenHFT/Java-Thread-Affinity.git
        </developerConnection>
        <tag>ea</tag>
    </scm>

</project>
